### ISSUE TITLE
Removing the 3 playstation BIOS

### ISSUE THREAD

**Issue by kivutar** [giongto35/cloud-game#130]
Since they are copyrighted, it's better to remove them from the repo.

**Comment by giongto35** [comment]
Hi Kivutar,

Thank you for your advice. These 3 ps bios I download from nightly build, so I thought it's free to use. Is there any good free bios I can use for PS . :D

**Comment by sergystepanov** [comment]
@giongto35, that must have been some sort of "alternative repo" (wink-wink) with nightlies, because it's illegal to share them. And as far as I know, there is an implementation of emulated HLE BIOS in the PCSX (not sure about its libretro [core](https://github.com/libretro/pcsx_rearmed)), so maybe it's worth a try.
Also, speaking of BIOSes, apparently some folks say that PSP has "[optimised](https://github.com/libretro/beetle-psx-libretro/issues/519)" PSX BIOS which allows to run games "smoother". It will be interesting to compare them without a frame rate cap.

**Comment by giongto35** [comment]
https://github.com/giongto35/cloud-game/pull/134
