### ISSUE TITLE
Performance graphs

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#142]
Add performance graphs as a naive visual performance comparison approach for:
 - frame render time
 - frame encode time
 - audio encode time
---
- Render as overlay into the game video stream.
   - graphs might render poorly due to vpx encoding garbage in the frame when CPU is overloaded
- Allow to set snapshot period for measuring mean values.
- Allow power-users to enable / disable such graphs in the app (unfortunately, everyone connected to the worker will see these graphs).
- Make this feature private or public.
- Alternatively, use `ws` per user performance graph data push, render overlay on the client-side. 

Current 100ms frametime counter as example:

![kkkddjdkkd](https://user-images.githubusercontent.com/846874/69745559-7fa99780-1153-11ea-9ae7-e71fa5a0a5d4.gif)

**Comment by giongto35** [comment]
This is the feature I really want at first place. Actually, I prefer to calculate the total time from frame emitted from emulator to when the user receives (But it is hard because we need to include frame start time all the way to the end) . But it's ok if we just track **encode time** + **render time** + **network time**.
The number is better done on front end side. And the data can be sent over Websocket.
I'm in progress of moving all Data Channel to Websocket now.

**Comment by sergystepanov** [comment]
@giongto35, yeah, I think server side renderer won't be possible because of encoding artefacts:

![kkkddjdkkdkk](https://user-images.githubusercontent.com/846874/69756306-3c5b2300-116b-11ea-80fa-292a8fab69bb.gif)
(all the graph dots should be red :/ )
On the front side it's much easier to draw graphs (:

**Comment by giongto35** [comment]
yes, but I don't prefer to overlay the image, :(
1) It's hard
2) increase load on server
3) network time is different between client
