### ISSUE TITLE
App hangs, freezes, stuck, and etc.

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#152]
@sergystepanov , @giongto35: Sorry for bothering you guys too much.

Freezes happen in different ways and happen more often with SNES and PSX. I will try to clearly report my experience:

GAME:
Yuu Yuu Hakusho - Tokubetsu Hen (J) .smc

1 - In the first test, it worked for 3 minutes squeezing all inputs normally until lock / freeze.

2 - In the second test, it crashed on the start screen with less than 1 minute.

3 - In the third test it worked for over 5 minutes.

The results are random and the duration too, but occurs with all games on these two platforms (SNES and PSX) with the following log.

<pre>
I0114 23:11:19.719963    3128 log.go:295] Viewport custom size is disabled, base size will be used instead 256x224
I0114 23:11:19.720074    3128 log.go:301] meta:  {assets/emulator/libretro/cores/mednafen_snes_libretro 256 224 44100 60 256 224 1.3333333730697632}
I0114 23:11:19.720278    3128 log.go:301] Video Encoder:  VP8
I0114 23:11:19.720460    3128 log.go:301] Enter fan audio
0.726540, 0.727273
listening audio channel true
I0114 23:11:48.217795    3128 log.go:295] ICE Connection State has changed: disconnected
I0114 23:11:48.217831    3128 log.go:301] ===StopClient===
I0114 23:11:48.218050    3128 log.go:301] Data channel closed
I0114 23:11:48.218070    3128 log.go:301] Closed webrtc
I0114 23:11:48.218116    3128 log.go:295] ICE Connection State has changed: closed
</pre>

If you prefer, I can record my screen and put it on youtube to check what happens.

Again, thanks for your attention.

_Originally posted by @Scatmannn in https://github.com/giongto35/cloud-game/issues/151#issuecomment-574451542_

**Comment by sergystepanov** [comment]
Had some spare time to test this issue on Ubuntu / Windows 10 and every single (runnable) game that you'd mentioned was working just fine, except one unrelated issue.

> Chrome: 79.0.3945.130 (Official Build) (64-bit)
> Ubuntu: 19.04

![Screenshot from 2020-02-01 16-38-28](https://user-images.githubusercontent.com/846874/73593240-e318c280-4512-11ea-9a65-859762d13f20.png)

@Scatmannn, maybe, there is an error in the browser console which could help. It opens on F12 in Chrome.

**Comment by DQ318** [comment]
Hello!
I am having a similar problem.
After assembling the application, nothing happens. Does not load any games and, in the Google Chrome console, errors appear as in the image.

Maybe some outdated dependency?

Using Ubuntu 19.10 - 64 bits

When using Ubuntu 18.04, I have the same error that Scatmannn reported.

![Captura de tela de 2020-02-18 20-34-05](https://user-images.githubusercontent.com/43095999/74787757-bb558880-528e-11ea-8464-8dcd77b5d8a9.png)

**Comment by DQ318** [comment]
I did some tests using other types of internet connections and apparently, they are all working very well. For every 10 tests, on average, only 1 had the error in question.

I think the "problem" is in the local connection, which apparently falls and causes the application to freeze.

**Comment by DQ318** [comment]
Taking advantage of the opportunity, I realized that, when establishing the connection with another user, Player 2 always enters the room with his game without sound, which only works if he modifies the controls.

I also realized that when establishing a new connection, player 2 always connects with control 1, it would be interesting to set it so that he would enter directly as control 2.

**Comment by giongto35** [comment]
Hi @DQ318 ,

Sorry for the late response, I didn't receive the notification :( 
1) 
> I did some tests using other types of internet connections and apparently, they are all working very well. For every 10 tests, on average, only 1 had the error in question. I think the "problem" is in the local connection.
Do you mean you cannot run the project on local environment? :/ I think it should work
and what is "internet connections"? do you mean browser? 
2) 
> Taking advantage of the opportunity, I realized that, when establishing the connection with another user, Player 2 always enters the room with his game without sound, which only works if he modifies the controls.
This is indeed the purpose due to the policy: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes 
In this policy, any audio cannot autoplay when a page is open. The browser requires the user to do some interaction before audio starts. 
3)
> I also realized that when establishing a new connection, player 2 always connects with control 1, it would be interesting to set it so that he would enter directly as control 2 by default.
It is indeed a feature I planned to have but I forgot, do you want to contribute for that :D
