### ISSUE TITLE
can the libretro support the platform arm64?

### ISSUE THREAD

**Issue by ChenRenHu** [giongto35/cloud-game#156]
when I try to build the worker using the flowing :

CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build cmd/overworker/main.go 

i got an error like this:
build github.com/giongto35/cloud-game/pkg/emulator/libretro/nanoarch: cannot load github.com/giongto35/cloud-game/pkg/emulator/libretro/nanoarch: no Go source files

**Comment by sergystepanov** [comment]
Hey @ChenRenHu, if you are asking if Libretro supports arm64 then the simple answer is [yes](https://buildbot.libretro.com/nightly/android/2020-02-01_cores/).
Now, if you want to compile `overworker` for this arch (arm64) and run it, as example on Adnroid, then, I'm afraid, it won't be that easy but it's possible. `Overlord` should compile without any problems right away. The main problem with the worker is the mandatory C code dependency. It won't even compile without `CGO_ENABLED=1`.
In order to build it (I'm just guessing) you need at least:
- install some C cross-compiler with arm support (e.g. gcc-aarch64-linux-gnu);
- install and setup all the needed C libs for arm64 arch: opus, opusfile, vpx, h264 (can be removed from the code which is easier than rewrite hardcoded C stuff), etc.;
- fix broken CGO linker dependencies and who-know-what errors if any.
Or something like that. I was able to compile it a tad further until missing arm64 libs on my Windows WSL Ubuntu with this:
```bash
CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc CC_FOR_TARGE
T=aarch64-linux-gnu go build -v -o ./bin/killme ./cmd/overworker
```

**Comment by ChenRenHu** [comment]
thx.  I'll try this way.

in reality, I want  to compile overworker  to work on Android, and then capture screen , and monitor 
by the browser. ^_^.

thx a lot.

**Comment by sergystepanov** [comment]
Sounds fun (: For Raspberries it should work, and it seems all the main cores are already (auto) [compiled](https://buildbot.libretro.com/nightly/android/latest/arm64-v8a/).
Also, I could port your arm64 build script into Github CI auto-builder here (along with Linux, MacOS, Windows builds), which will add to the project pretty soon, if you want it for some reason (:/

**Comment by sergystepanov** [comment]
I'll probably look in to that later.
