### ISSUE TITLE
Cann't find the Game

### ISSUE THREAD

**Issue by hhuchzh** [giongto35/cloud-game#185]
I follow your guide to deploy the whole test environment, but when I use chrome to connect the server, I can see the game manage window but there is no game show in the window, anyone knows the reason?

**Comment by giongto35** [comment]
Can you send us the browser console? Maybe it failed to setup

**Comment by hhuchzh** [comment]
> Can you send us the browser console? Maybe it failed to initialize the connection

Thank you for your reply. I forgot to explain that I deployed the environment in the AWS. Not in the local server. Then I used my local PC to connect the server, bellow is the browser console.

 [input] keyboard has been initialized log.js:9:45
[input] joystick has been initialized log.js:9:45
[input] touch input has been initialized log.js:9:45
Firefox can’t establish a connection to the server at wss://161.189.174.55:8000/ws?room_id=&zone=. socket.js:41:15
[ws] [object Event] log.js:15:47
[ws] closed


Does this mean that project can only be run locally?
Thank you.

**Comment by giongto35** [comment]
@hhuchzh I had some customized setup to have it run on production. One reason is because of security. I support HTTPS on the server and HTTP on the local. The WSS you see it websocket secure.
The param to run on prod:
`coordinator --mode prod --domain cloudretro.io` : flag mode prod , domain is the domain nam
`worker  --mode prod --coordinatorhost cloudretro.io`: flag coordinatorhost to specify the domain to connect to.

I think you can check if it's successful to run with those params on your remote host first. If the backend can be spawned up, I think you are able to connect to it.
