### ISSUE TITLE
Improve WebRTC lag

### ISSUE THREAD

**Issue by 88hcsif** [giongto35/cloud-game#198]
So far I have only tried to play Mario Kart 64 with the added N64 support.
I tried battle games with friends and it is playable.
But as soon as I try to do a race even with one player the lag becomes too long.

I checked and the Raspberry Pi is coping fine with the emulation and the video encoding.
Mario Kart 64 runs at around 29 frames per second.
Between receiving an input change from the client, giving it to the emulator, drawing the next frame, encoding in h264 or vp8, and sending the frame takes anything between 50 and 100 ms.

I think the problem is in the video player on the client side (this is on Chrome).
Probably, I will make a PR at some point to add this extra data to the stats view.
If I get the stats for the RTCPeerConnection and I look at the video track while playing a race I can see:
<pre>
Report: track
ID: RTCMediaStreamTrack_receiver_52
Timestamp: 1592167875098.266
trackIdentifier: video
remoteSource: true
ended: false
detached: false
kind: video
jitterBufferDelay: 77.946
jitterBufferEmittedCount: 2883
frameWidth: 320
frameHeight: 240
framesReceived: 2945
framesDecoded: 2883
framesDropped: 0
</pre>

There is a big difference between framesDecoded and framesReceived.
At 29 fps the lag due to this is about 2 seconds.
I am completely new to WebRTC so I am not sure exactly what is going on...

**Comment by sergystepanov** [comment]
WebRTC is _amazing_ piece of technology (: It's been 10 years and it is still in drafting experimental state even today, after 2 years since a first stable release, with a lot of bugs in their tracker.
I thought before about this lip sync (how it's called in WebRTC) issue but I haven't had time to try to understand it and read some [books](https://github.com/runner365/read_book/blob/master/RTP_RTCP/RTP%EF%BC%9AAudio%20and%20video%20for%20the%20Internet.pdf). What I can tell for sure: it is not Libretro issue. My guess, since we are not using any kind of A/V synchronization when encoding two separate streams in two separate (sic!) threads (channels), it's only matter of time when everything goes out of sync.
If you want to reproduce this issue, just make the OS scheduler to starve worker thread (with heavy load on the same system or something like that). After that you will get a couple second delay of the video stream. It is strange that A/V delays are going down on the graphs but WebRTC mixer will be playing it with a constant desync until session reset.
Maybe it can be fixed like [that](https://bugs.chromium.org/p/webrtc/issues/detail?id=5912) by setting same msid, or single-threaded encoder, or server-side A/V muxer.
Maybe, you might want to try to look into it, since you are interested (:
And I think we are all new to this WebRTC stuff.

**Comment by giongto35** [comment]
Sorry for the late response,
Do you experience the lag with non-gl core? Is the lag gradually increases over time? Sometimes, it is because un-reclaimed memory get accumulated.
I never notice framesReceived and framesDecoded stat but it seems to affect the lag indeed. We can verify it if you test with lighter games (non-gl) and it is still lag.

**Comment by 88hcsif** [comment]
I now tried on Chrome, Firefox, and Safari and they all show the issue with more or less the same severity.

framesDecoded/framesReceived are part of the https://www.w3.org/TR/webrtc-stats/ API.
Unfortunately Firefox only keeps track of framesDecoded and not of framesReceived so it is hard to tell how many frames behind the video is lagging.

So far I only tested with Mario Kart 64 (N64), Super Mario (NES), and Sushi the Cat (GBA).
With Super Mario there is rarely a bit of lag when the level starts but the stream quickly recovers.
Sushi the Cat is similar but the lag when the level starts is not rare, it is pretty consistent.

What I think is happening with Mario Kart 64, is that the fps are not stable.
(I am measuring the fps on the backend before the image channel fanout) 
When I start a race the fps are around 20.
If I crash into a wall or I stop, the fps actually increment to about 29 and that is when the lag seems to start building up.
I cannot quite find a precise pattern of what happens to the lag.
I would say that most of the times it builds quickly from 0 frames to around 80 and then it keeps increasing slowly and have seen get as high as 300 frames.
If the lag started because I stopped moving and I then start moving again, then the lag usually start decreasing.
Other times it just decreases while I am still stopped (in both cases I wait the same amount of time).

So again, my guess is that the webRTC client on the browser is not coping very well with quick changes in fps...
I will look to see if there is any way to reset the stream when the lag (the frames received but not yet decoded) starts to build up...

**Comment by giongto35** [comment]
Don't know if it apply to this scenario. You mentioned when the car stops, the lag accumulates, when the car start running, the lag decrease right?
So it's like this I think: 
- Car stops => less logic in game => higher FPS (29fps for example) => more frames are pushed to render in a second => WebRTC encoding or WebRTC rendering frames are capped (20 fps for example) => Frames are queued up to render and starts lagging.
- Car runs => more complicated logic in game => lower FPS (15fps for example) => less frame are pushed to render in a second => WebRTC encoding or WebRTC rendering frames are still capped (20 fps for example) => queued frames get free up

Besides, one comes from my experience that I want to share is : the latency is also affected by encoding system. According to video encoding algorithm, frame with higher entropy will take longer time to encode and decode. For example, flipping from a black screen to game screen, it will take time.

**Comment by 88hcsif** [comment]
Yes, I agree with your summary.
And I also think that fps improve when the car stops for a combination of "less logic in game" and "encoding is easier because there are fewer changes between frames".
I will try to run the server on something a bit more powerful than a Raspberry Pi to see if the fps stay more consistent.

When you say that WebRTC frames might be capped, is this something that you have seen before? is it something controlled by the sender or by the receiver? is it something we can control?

**Comment by giongto35** [comment]
The reason I say that rendering is capped because the input of rendering pipeline is series of fixed size images. This rendering/encoding pipeline is abstracted away from game logic, and its input size is always the same, so the performance is a constant.

I think we can measure or bench the encoding pipeline first:
- Giving 60 frames of size 240*360, how long it takes to fully encode them.
- How many frames of size 240*360 the encoding pipeline can proceed in 1 second.

After we can define the bottleneck in the rendering pipeline. We have 2 options:
- Improve the encoding pipeline, make it at least as fast as game logic
- Limit number of frames game logic to push to render. For example, if game logic produce 60FPS while the rendering can just proceed 30FPS, we only push 30 frames among 60 to render from game logic to the rendering.

**Comment by 88hcsif** [comment]
I see. I think in the Raspberry Pi, the encoder is the bottleneck.
I am trying to get everything to run on a Mac but I am struggling to compile Mupen64plus on Mac (it is not available in Retroarch), and I want to avoid comparing apple and oranges.

I think the rendering pipeline output rate is not quite constant because frames can be dropped.
The channel sizes are:
- NAEmulator/room: 30
- VPXEncoderInput: 2 (capacity check before pushing new frame in)
- VPXEncoderOutput(fanout input): 10 (capacity check before pushing new frame in)
- WebRTC(each fanout channel): 30
If the pipeline can cope with the game rendering, the pipeline output rate is identical to the game output rate, it is just shifted in time.
If the pipeline cannot cope with the game rendering the output rate will depend on how many frames are dropped at each stage, which may vary over time depending on the machine resources.
I think there are cases with the Pi where it drops frames because the channels are full.
In general I like this approach, I prefer to drop a frame rather than stretching the pipeline and increasing the lag, but I will do some tests to see how frames are dropped.

My main reasoning for opening this issue though, is to investigate the browser rendering pipeline.
My theory is that, in certain situations, the WebRTC client in the browser is buffering frames and causing lag.
Unfortunately we do not have much control over the browser code, but there might still be some things we can do to avoid hitting these code paths in the browser.

**Comment by 88hcsif** [comment]
I asked for some help in Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=1098514) and the current theory is that the browser is doing the right thing because it is receiving incorrect timestamps for the RTP packets from the WebRTC server.

It seem that the WriteSample function that we use from Pion WebRTC is only designed for constant frame rate streams and therefore we need to change it to cope with variable frame rate.
I am guessing that the Raspberry Pi is an extreme case because of the limited architecture, but I also think that in general it is unrealistic to expect that the pipeline is always coping with the game rendering so I think it is worth to make this change.

I will look into the best way to generate our own timestamps for the RTP packets.

**Comment by giongto35** [comment]
@88hcsif Oh, nice. Sean even join and answer the question and confirm it is the `WriteSample` problem. 
Just learn about this timestamp from the topic as well. That's right from the WebRTC, so it's how they control the rate. So is there any follow up after the chromium post?

**Comment by 88hcsif** [comment]
I went ahead and played with it and I have a PR ready.
I do not know for sure if this is what Sean had in mind but I am guessing so.
