### ISSUE TITLE
Delays of media pushing to the clients

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#265]
When we push audio and video packets (fan-out) sequentially in a for loop to all connected WebRTC peers, every next client will have a growing delay as a sum of packet push processing time of all previous clients.
To consider doing that in parallel.

**Comment by giongto35** [comment]
I doubt it will affect performance, do you have any evidence?
I think the push to clients is asynchronous, so the peer will receive frame over channel and process later. Processing will be done parallelly now. 
There can be a scenario that we got blocked when pushing the frame to a peer because the peer is busy processing and not accepting on that channel.

**Comment by sergystepanov** [comment]
You can try to create a shared game and open 20 tabs of this game then compare delays on the first tab and the last opened.
I'm talking about these loops and their iteration time. I think they should be non-blocking and parallel. Maybe add a simple debug timer for measuring the time elapsed since the loop start.
https://github.com/giongto35/cloud-game/blob/a4d38b41a076a6b66cb6006e7839acbb6b740781/pkg/worker/room/media.go#L107
