### ISSUE TITLE
Can you recompile the websites that use your cloud-game?

### ISSUE THREAD

**Issue by ImanCol** [giongto35/cloud-game#303]
I'd like to test the websites that are adding your great work. Kosmi seems to use Webrtc but his emulators are clunky.

Oh if the cloudretro website could add our own Roms, it would be great, in a way (using the ones hosted on archive.org)

**Comment by sergystepanov** [comment]
Hey @ImanCol! Thanks for the interest.
Correct me if I'm wrong, you are asking for a list of public sites that are using cloud-game code and where you can play some games, right? I can't think of any other sites except cloudretro.io. @giongto35, do you know any?

Now, on the second part of your message. Allowing to upload arbitrary user ROMs on the main site would be too risky due to copyright and piracy concerns. On the other hand, allowing users to download and play some free/public games from some catalog may be an interesting idea for further consideration.
archive.org is hosting mainly desktop computer games, except the old Atari console ROMs, if I remember correctly, so it's not really suited for this project dedicated mainly to retro consoles gaming.
@giongto35, what do you think?

**Comment by giongto35** [comment]
@sergystepanov I think roms request is top 1 frequently asked question. CloudRetro.io is hosted on my infrastructure, and it is serving as the demo of the open-source, not a production. I'm feeling an unhealthy trending that people expect CloudRetro.io is a completed product and request game feature on top of that.

So here, I would expect users to host their own infrastructure and adding their own roms. We try to make that hosting process is easy as possible.
Or if we really want to have ROMs adding utility on CloudRetro.io, we can consider building a user system and different repo for each user or may just allow everyone uploads to the same repo so that we can keep enriching the game list. We don't let user download game, so I don't know if we violate copyright and privacy somehow.

**Comment by sergystepanov** [comment]
> Copyright infringement (colloquially referred to as piracy) is the use of works protected by copyright law without permission for a usage where such permission is required, thereby infringing certain exclusive rights granted to the copyright holder, such as the right to reproduce, distribute, display or perform the protected work, or to make derivative works. The copyright holder is typically the work's creator, or a publisher or other business to whom copyright has been assigned. Copyright holders routinely invoke legal and technological measures to prevent and penalize copyright infringement.

If a game is not opensource or free for use or not licensed (bought) for public use then letting play or just display it is technically copyright infringement. There is a thing called [fair use](https://en.wikipedia.org/wiki/Fair_use) doctrine in the US law but I'm not sure how it applies or if it applies at all to our research purposes.
It would be nice to have some ROM management capabilities for sure.

**Comment by ImanCol** [comment]
Oh I understand. Thanks for all the responses from her.

Sorry if I was misunderstood, my English is not very good, but I really wanted to know more about this project, mainly because IT IS THE BEST CLOUD GAMING AND FREE ACCESS THERE IS !. Mainly because I see that I was able to play a game of GBA (or Gameboy Color?), And Metal Slug so smoothly. Even Kosmi doesn't feel as good playing SNES as his big WebRTC project does.

In any case, I don't want them to abandon this project, he has an impeccable job and makes good use of WebRTC. I found it with the desire to be able to share a game with someone with the lowest latency. But although the list of games is very short and I cannot recognize all the emulators that are used, I cannot find or recognize any website that uses your project.
So I wanted to know which pages are using his project and adding more emulators.

But I already want to know that other emulators are compatible? And hopefully you can help me configure it in my own environment.

Thank you for your time and this great project.

**Comment by giongto35** [comment]
Thanks for the compliment.

There is no integration with CloudRetro now, and Integration is not part of CloudRetro. You can only run CloudRetro on CloudRetro.io.
And do you mean you want to integrate Cloud Retro with Kosmi?

**Comment by ImanCol** [comment]
Kosmi is not mine, it is just a webparty that accepts nes, snes and psx. The latter is unstable.

I just want to know how to integrate NEW EMULATORS in Cloud Gaming on my PC, or to know from the testing that you have done, which ones are compatible.

**Comment by sergystepanov** [comment]
Basically, it can run any emulator that Libretro [can](https://docs.libretro.com/meta/core-list/).
Be aware that we don't have all the extended controller input support such as R2 L2 buttons, second analog stick from the PS and etc.
You can check the current list and add new emulators in the config file at the `libretro.cores.list` key:
https://github.com/giongto35/cloud-game/blob/569ed4c0ccc93d2816ad356b9c4a79496ae6ce40/configs/config.yaml#L115-L124
In case if you want to add a new emulator, you either download and put one that you need for your OS from [here](http://buildbot.libretro.com/nightly/linux/x86_64/latest/) (these are for Linux, different OSes are there too) or just get the emulator name from this list and add a new entry to the config file (you can probably guess params from already present entries), it will download it automatically for your OS. As an example, I want to add 3DS then I'd rite something like this:
```
  3ds:
    lib: citra_libretro # the name
    roms: [ "3ds", "cia" ] # ROM file names
    # add config: citra_libretro.cfg if you want for manual core config
```
