### ISSUE TITLE
Sending only video difference seams to be removed

### ISSUE THREAD

**Issue by nimamoradi** [giongto35/cloud-game#321]
The was a feature for your project that will only send video stream pixel difference that caught my attention and I want to implement it for my webrtc game too, but this one is mobile.
For finding the difference and sending only that part.
I found the code before here https://github.com/giongto35/cloud-game/blob/77d7a7383feec8c14dc82dc4d1706de0870b620c/pkg/encoder/vpx-encoder/tools_common.c#L606
. I want to know is what was the reasons to omit that. I did not found the commit and the reason it got deleted from issues also

**Comment by sergystepanov** [comment]
1. I rewrote all encoders in order to fix some bugs and make them compact removing dead code.
The source code for libvpx is [here](https://chromium.googlesource.com/webm/libvpx/) and that's the place from where it was copied into cloud-game originally. This function had never been used anywhere here.

2. I think you got the wrong idea about that function. After a quick search, I found that it was introduced [here](https://chromium.googlesource.com/webm/libvpx/+/c10833faa65b2859231f4ab58c5da73a52168863), used [here](https://github.com/webmproject/libvpx/blob/705bf9de8c96cfe5301451f1d7e5c90a41c64e5f/examples/vp9cx_set_ref.c#L71-L104):

> Test decode and find mismatch in vp9 svc example encoder.
> Also write it to opsnr.stt when internal stats is enabled.
> Removed some redundant code in vpxenc.c and vp9cx_set_ref.c

It's used just for comparison of source YUV image to a decoded one in tests. It returns a bounding box where the differences are for each plane, I guess. We don't send raw YUV images to the clients, we send x264 or vp8 compressed frames into the browser's decoder.
This file `tools_common.c` is a bunch of various helpers not required for the main lib.

**Comment by nimamoradi** [comment]
@sergystepanov thank you for your response. I did get it wrong sorry for that. But in [webrtc hacks website](https://webrtchacks.com/open-source-cloud-gaming-with-webrtc/) which is some kind of doc for this project in the ``Video Compression`` part, the author stated that he only sends the different parts.

> The idea of video compression is to omit non-essential bits of information while keeping an understandable level of fidelity for users. In addition to encoding individual static image frames, the algorithm made an inference for the current frame from previous and future frames, so only the difference is sent. As you see in the the Pacman example below, only the differential dots are transferred.

Could provide me the section that implements that.

**Comment by sergystepanov** [comment]
@nimamoradi, thanks for the link, now I see how it might be a little bit confusing. By `the algorithm` he meant a video codec's compression of the frames. I believe, this article was heavily redacted under a time crunch, so it is not surprising that it may contain ambiguous parts.
Anyways, you shouldn't worry about this stuff. Any video codec supported by WebRTC can be tweaked to your preference on the server and includes a huge amount of optimizations. In the current state, video codecs noticeably outperform even common image compression algorithms (e.g. gif vs webm). But if you want to roll your own ~crypto~ image compression, sure, it could be a fun exercise, I guess. (:
Feel free to ask any further questions or close this issue otherwise.
