### ISSUE TITLE
server panic when use invalid ext name

### ISSUE THREAD

**Issue by xxxsen** [giongto35/cloud-game#333]
using a nes game with zip format may cause server panic.

log here: https://pastebin.com/h5J1xxzW

by the way, is it possible to store different game with different folder like retropie?

![image](https://user-images.githubusercontent.com/3880276/127173972-8b5add0e-cd29-4594-a990-0e22391e9629.png)

**Comment by sergystepanov** [comment]
By design, each emulator has a predefined list of ROM file extensions and these file extensions can be used with more than one emulator. So when you are trying to open zip, it opens with MAME (FBneo) core (see the config file).
Other Libretro frontends read ROMs with the help of special ROM-list files which is quite tricky to implement.

I think it won't read subfolders therefore you can store games only in one folder (assets/games), and when it reads the folder, any ROMs with exact same filenames will be skipped.

**Comment by xxxsen** [comment]
Other Libretro frontend use a config file to definite which folder should be used for emulator to load their roms, by the way, gamelist.xml is optional, they will read roms in folder when there is no gamelist.xml in folder by scanning files too.

Additionally, reading an abnormal file will cause the server panic is not a good design.

**Comment by sergystepanov** [comment]
> Other Libretro frontend use a config file to definite which folder should be used for emulator to load their roms

That's actually an interesting approach. Maybe I'll implement it later.

> Additionally, reading an abnormal file will cause the server panic is not a good design.

I agree but all the crashes are expected to be handled with Docker / k8s resilience features.
