### ISSUE TITLE
USB gamepad

### ISSUE THREAD

**Issue by discordfar** [giongto35/cloud-game#414]
i Try it at https://cloudretro.io/

usb gamepad work in normal screen but automatic config keys and lag controls
not remap, not work on full screen

**Comment by sergystepanov** [comment]
@discordfar

If I understood you correctly, gamepad bindings do not work in the fullscreen mode?
Could you clarify what is lag controls?
I'll try to look at this problem when I have time.

**Comment by discordfar** [comment]
@sergystepanov

Exactly, usb gamepad not working in fullscreen mode
and lag, delay on d-pad

**Comment by sergystepanov** [comment]
Ah, I see.
The fullscreen stuff is probably a bug. Will look and fix later.
Button remap is not supported for controllers atm and just hardcoded here https://github.com/giongto35/cloud-game/blob/master/web/js/input/joystick.js#L98. 

And about d-pad delay. Do you mean it only lags on gamepad and does not on the keyboard controls? Even now?
Otherwise cloudretro.io may be slow with some games, and there is a bug that I'm currently trying to fix which causes severe slowdowns on cloudretro.io.

**Comment by discordfar** [comment]
d-pad delay on usb gamepad
ty nan
