### ISSUE TITLE
[Question] supported game system?

### ISSUE THREAD

**Issue by discordfar** [giongto35/cloud-game#417]
@sergystepanov

which system supports?
support neo geo cd?

this cloud-game can run specific system only? or run all?

**Comment by sergystepanov** [comment]
Here is the default list (for cloudretro.io also) https://github.com/giongto35/cloud-game/blob/master/pkg/config/config.yaml#L189.
An yes, you can add there your own, like NeoGeo CD. 
It was tested with nes, snes, gba, mame, psx, n64, but in theory it may run any Libretro core with CPU or OpenGL emulation (backend). But keep in mind that cloud-game has a lot of missing parts compared to Retroarch (the reference Libretro frontend).
So, cloud-game can load any ROM (that are scanned at the start of the app) from that list of Libretro cores in the configuration file.
In debug mode (see the config) it will print all the ROMs found into the console, like:
```
14:03:02.1852 3a9c DBG c     Lib dump
--------------------------------------------
--- The Library of ROMs                  ---
--------------------------------------------
     snes   Earthbound (U) (Earthbound (U).smc)
     pcsx   Mega Man X4 (USA) (Mega Man X4 (USA).chd)
      nes   bad_apple_2_5 (bad_apple_2_5.nes)
      nes   Alwa's Awakening (Demo) (Alwa's Awakening (Demo).nes)
      n64   Legend of Zelda, The - Majora's Mask (U) [!] (Legend of Zelda, The - Majora's Mask (U) [!].z64)
     pcsx   Xenogears1 (Xenogears1.cue)
     pcsx   WWF WrestleMania - The Arcade Game (USA) (WWF WrestleMania - The Arcade Game (USA).chd)
    dosbox   shocktro (shocktro.zip)
      nes   Nekketsu Kakutou Densetsu (Japan) (Nekketsu Kakutou Densetsu (Japan).nes)
      nes   R.C. Pro-Am 2 (U) [!p] (R.C. Pro-Am 2 (U) [!p].nes)
      n64   Sample Demo by Florian (PD) (Sample Demo by Florian (PD).z64)
      n64   Super Mario 64 (USA) (Super Mario 64 (USA).z64)
     pcsx   Mega Man X4 (U) [SLUS-00561] (MegamanX4\Mega Man X4 (U) [SLUS-00561].cue)
      nes   Super Mario Bros. (World) (Super Mario Bros. (World).nes)
      nes   dpadhero2 (dpadhero2.nes)
     mame   ddsom (mame\ddsom.zip)
    dosbox   shocktro (1) (shocktro (1).zip)
      nes   Super Mario Bros. + Duck Hunt (USA) (Super Mario Bros. + Duck Hunt (USA).nes)
      gba   anguna (anguna.gba)
      gba   butano-fighter (butano-fighter.gba)
     mame   1945kiii (mame\1945kiii.zip)
...
```

**Comment by discordfar** [comment]
nice many details
many thank man
cheers!

**Comment by sergystepanov** [comment]
Either [here](https://github.com/giongto35/cloud-game/blob/master/pkg/config/config.yaml#L63) or as a system environment variable like [here](https://github.com/giongto35/cloud-game/blob/master/docker-compose.yml#L14) (almost all config params can be set as system env vars with the prefix CLOUD_GAME_.

**Comment by discordfar** [comment]
In which folder is the core libreretro located?
for add neocd

**Comment by sergystepanov** [comment]
Most of your questions should be clear if you read the comments in the `config.yaml` file.

For NeoGeoCD it's something like this:

Read the core [docs](https://github.com/libretro/neocd_libretro).
Change `cloud-game\pkg\config\config.yaml` as shown bellow. The app will download the core automatically into `cloud-game\assets\cores` after restart.
```diff
list:
+ neocd:
+   lib: neocd_libretro
+   roms: [ "cue", "chd" ]
+   folder: neocd
  gba:
    lib: mgba_libretro
    roms: [ "gba", "gbc" ]
```
Add any NeoGeo CD BIOS to `cloud-game\libretro\system\neocd`.
Add game ROMS into `cloud-game\assets\games\neocd`.
Play games.

![image](https://github.com/giongto35/cloud-game/assets/846874/46d32530-62ae-441d-aff1-cb45b8782cdd)

**Comment by discordfar** [comment]
i go read all doca
many thanks men
cheers!

**Comment by discordfar** [comment]
@sergystepanov

please, you can share cores?

**Comment by sergystepanov** [comment]
If you want to find them manually, here is the link https://buildbot.libretro.com/nightly/ (have you read config.yaml?). They are system dependent.

(since you've mentioned mupen64plus_next_libretro.cfg file, it was in the very old version of cloud-game so make sure you have the latest version of the code from this repository)

**Comment by discordfar** [comment]
Which one is compatible with your system?
i need get cores for test

![cores](https://github.com/giongto35/cloud-game/assets/142048925/cafd519a-4915-4449-a004-ded50506c437)

**Comment by sergystepanov** [comment]
Something tells me that you didn't read or understand my previous replies. So I think, cloud-game is a bit complex for you to use, and you would have better chances with [Retroarch](https://www.retroarch.com/) if you just want to play some games.

I assume that you've downloaded and using compiled cloud-game v2.6.1, don't use it, it's old and obsolete. I don't remember if my instructions can be applied to this old version. The version you need is the one that you have to download and compile from the latest git snapshot. 
If you want to find and download cores for some reason _manually_, which is not good option, then here they are  https://buildbot.libretro.com/nightly/windows/x86_64/latest/. Find needed, download, and extract dll to the `assest/cores` folder, but you need to add the record about this core into the `config.yaml` file also. You see, if you add the record first and just run the app (without downloading the cores), **the app itself will download this core to you system (windows) automatically**.
Also, NeoGeo CD requires a BIOS in order it to boot games. This is not related to cloud-game, but I'm sure you will have troubles with it too.
So, I don't think cloud-game is the right choice for you to use, since those previous quite straightforward instructions are causing such troubles. 

P.S. Googling questions helps in 95% of the cases.
