### ISSUE TITLE
Have any plan support the android emulator? 

### ISSUE THREAD

**Issue by zct** [giongto35/cloud-game#59]
I'am very appreciate this project

**Comment by giongto35** [comment]
Thanks @zct. It's really good idea. I need to check if it is possible to run setup Android emulator on linux environment and stream out and in user interaction. Android has many user interactions, so it might not be easy to support it but I will try.

**Comment by michaelantonio** [comment]
Hello @ giongto35 I am writing from Spain, to tell you that this project is almost something that most of us as developers and analysts admire is incredible and from here I thank you for bringing this incredible thing to light ... development you come up with several proposals or doubts, so I was taking a little bit over the code and where it is hosted .. since everything is directed to the cloud and this is practically the finished structure because it does not take advantage of the retroarch apis that ahy are all the structured emulators structured and take advantage of the cloud because it would be incredible to be able to research and continue developing games in the cloud and execute them, since there are many projects already on the street like "HATCH IS vodafone"  https://playhatch.com/ ,is new or VORTEX I would love to help you to take the project forward with donations and that the community will help you and the developers who are behind ... I hope your answer

**Comment by michaelantonio** [comment]
Hello @ giongto35 I am writing from Spain, to tell you that this project is almost something that most of us as developers and analysts admire is incredible and from here I thank you for bringing this incredible thing to light ... development you come up with several proposals or doubts, so I was taking a little bit over the code and where it is hosted .. since everything is directed to the cloud and this is practically the finished structure because it does not take advantage of the retroarch apis that ahy are all the structured emulators structured and take advantage of the cloud because it would be incredible to be able to research and continue developing games in the cloud and execute them, since there are many projects already on the street like "HATCH de vodafone"  https://playhatch.com/,  is new or VORTEX I would love to help you to take the project forward with donations and that the community will help you and the developers who are behind ... I hope your answer

**Comment by giongto35** [comment]
Thanks @michaelantonio, I'm really happy that you like this project. You comment motives me a lot because maintaining this project costs me time and burns my pocket also.
This project starts as my experimentation but now I also aware that some programmers are also willing to contribute to this project. I'm really happy about it as well as feeling more responsible for its development and extension. I think to take project further, I need a clear roadmap and find the right direction for it. I'm working on the plan and will update soon. My idea currently is to generalize it and bring a gaming interface, so it will no longer be tightened with an emulator.

**Comment by michaelantonio** [comment]
@giongto35 of course I support you and I will make your project known here in Spain since we are several developers that we try to investigate and innovate and your project is incredible .. and I know that carrying this forward is complicated and difficult so when you decide to put a quantity to get the project ahead we will support you both economically, publicity and the way forward ok ... we will be attentive to your evolution for any help you need

**Comment by giongto35** [comment]
Thanks @michaelantonio very much for your support. I will try my best to continue working on it. I hope you will continue to follow it and the result will enlighten you. :D
