### ISSUE TITLE
Collaborative gameplay

### ISSUE THREAD

**Issue by smasher164** [giongto35/cloud-game#69]
Is it possible for two people to play in the same room? If so, I would like to request, and possibly help implement this feature. I imagine that the inputs from both clients would be sent such that a single game is controlled by both.
Thank you!

**Comment by giongto35** [comment]
Hi @smasher164,
Yes, that feature is definitely the one I'm looking for!! It is a possible thing that can enhance the gaming experience. It is awesome that we can bring online gaming to retro game. 
That logic of collaborative gameplay was in the code before but after some interaction, it is not maintained and not worked anymore.
----
The flow I'm looking for is:
1) The first user runs a new game.
2) That user share the game (Click share button. Sharable link is copied to clipboard)
3) The second user joins the same game by accessing that sharable link
4.1) The second user will use W,A,S,D, H,J,K,L. 
4.2) The second user's input still use Arrow Key and ZXCV. These key are later mapped to second controller in the code.
----
Currently, The code supports 1,2,3. I think you can pick either 4.1 or 4.2 approaches. 4.1 is easier when you don't need to know if the player is the first or second because arrow keys and WASD are separated, you can just send the input as it is. 4.2 is harder because we need to determine the index of the player and do a correct input mapping.

You can take a look at those files
https://github.com/giongto35/cloud-game/blob/master/worker/room/room.go#L188 <- Input mapping can be done here
https://github.com/giongto35/cloud-game/blob/master/emulator/gameview.go#L195  <- NES Emulator second controller input
https://github.com/giongto35/cloud-game/blob/master/libretro/nanoarch/nanoarch.go#L79 <- Libretro Emulator input (you may not need to consider implement for this one, LibRetro is a generic emulator based on RetroArch)
https://github.com/giongto35/cloud-game/blob/master/static/js/ws.js#L274 (Legacy playerIndex)
I have some attempts to introduce playerIndex in the code. However, currently, playerIndex is from frontend payload and always set with 1. Feel free to make anychange on that

Thank you very much for your help :D

**Comment by smasher164** [comment]
> I think you can pick either 4.1 or 4.2 approaches.

Many games have both a single-player **_and_** local multi-player. 4.2 implies that we restrict controller input to the first or second controller input, unless we provided UI to distinguish the player index. 4.1 is the simplest option that doesn't introduce new UI. Both clients can use ZXCV🡑🡓🡐🡒 to control player 1, and HJKLWASD to control player 2.

**Comment by giongto35** [comment]
It's correct. 4.2 requires extra logic to determine player index based on number of rtcSessions in that room. e.g: If there is already a player, the next user index will be player 2 and if there are already 2 players, the next one will be player 3. It can serve the multiplayer game with more than 2 users. In that way we don't need to introduce new UI.

I consider 4.2 is the ideal approach but 4.1 is much simpler and the result is still awesome. So if you can work on 4.1, I still really appreciate it.

**Comment by smasher164** [comment]
Just to be clear, this feature request is for collaborative gameplay, not necessarily multiplayer. If I understand you correctly, 4.2 says "based on the number of rtcSessions, we can assign the next player to an index as player n".
However that implies that although this is legal:

Client | Player
--- | ---
1 | 1
2 | 2
3 | 3

This is not:

Client | Player
--- | ---
1 | 1
2 | 1
3 | 2

This feature request asks to make the second example legal. In order for two clients to have the same player number, I don't see how the number of rtcSessions can help. The client would have to explicitly specify the player number it wants to send its input as.

**Comment by giongto35** [comment]
Got your point!
Yes, I know about TwitchPlaysPokemon. It's very interesting gameplay and can drag a lot of interaction. I hope to support both collaborative + multiplayer but seems like it's hard with current UI. 
I think you can to move forward with collaborative, I really like to see it in action. Let me know if there is anything I can help to explain during the implementation.
