### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#91]
It seems there is no audio when you run games on the cloudretro.io or locally.
Maybe I missed that point in the docs, but does it support audio decode/playback right now?
Tried the latests versions: 
W10 / Chrome (Stable, Dev, Canary), 
Ubuntu 18 / Chrome (Stable), 
Android 8 / Chrome (Stable).

**Comment by giongto35** [comment]
Hi sergystepanov,
The audio is not worked properly right now after my attempt to integrate with LibRetro. And because of autoplay policy, https://developers.google.com/web/updates/2017/09/autoplay-policy-changes, I decided to mute the audio.
https://github.com/giongto35/cloud-game/blob/master/web/game.html#L36
The attribute is `mute`.
I'm welcoming for any change that can help improve the audio encoding pipeline.

**Comment by sergystepanov** [comment]
Oh, that was easier than I thought. (: Thanks for the info. 
P.S. I wish I could help you with this project but, sadly, I'm too don't have that much spare time for hobby projects and mostly lacking in exp with C/GO programming. I've just started to write my own frontend from a scratch based on your work (and nano/no arches) in order to understand libretro. Now, that you've mentioned some audio problems, maybe I'll look into that when I get to that part.
Thanks for your great work, it helps a lot to beginners like me.
